version: '3'

services:
  
  daemon:
    image: epik/go-epik
    build:
      context: ./
    ports:
      - '1234:1234'
      - '1347:1347'
    volumes:
      - .:/opt/epik
      - ./.epik:/root/.epik
    environment:
      - PROCESS=daemon
    command: bash docker/scripts/setup.sh

  # miner:
  #   image: epik/go-epik
  #   build:
  #     context: ./
  #   ports:
  #     - '2458:2458'
  #   volumes:
  #     - .:/opt/epik
  #     - ./.epikminer:/root/.epikminer
  #   environment:
  #     - PROCESS=miner
  #     - COINBASE=
  #     - FULLNODE_API_INFO=
  #   command: bash docker/scripts/setup.sh